### ISSUE TITLE
Adding "share via email"

### ISSUE THREAD

**Issue by cfunc** [tabalinas/jssocials#1]
Hi there,
Great plugin, very well done!
I would like to know though, is it possible to add an extra option to share pages via email?
Thanks :)

**Comment by tabalinas** [comment]
Hi, Thank you!
Yes, I'm gonna add build-in email sharing soon. Thank you for the request!

For now it's easy to add it from out side with the code:

```javascript

jsSocials.shares.email = {
    label: "E-mail",
    logo: "fa fa-envelope",
    shareUrl: "mailto:?subject={text}&body={url}",
    countUrl: ""
};

$("#share").jsSocials({
    shares: ["email", "twitter", "facebook", "googleplus", "linkedin", "pinterest"]
});

```

And add css, e.g. for the flat theme:

```css
.jssocials-share-email .jssocials-share-link {
  background: #0a88ff; }
  .jssocials-share-email .jssocials-share-link:hover {
    background: #006ed6; }
```

Or even better to get the src, add the email color to `_shares.scss`, and build with grunt css for all themes:

```scss
$share-names: ('twitter', 'facebook', 'googleplus', 'linkedin', 'pinterest', 'email');
$share-colors: (#00aced, #3b5998, #dd4b39, #007bb6, #cb2027, #0a88ff);
```
