### ISSUE TITLE
do you know how i can use php code for the pintrest image

### ISSUE THREAD

**Issue by annettek** [tabalinas/jssocials#14]
<?php echo $image['popup']; ?>

image: " ",

can this be used as the image for pintrest so that it share the image from the product i am on. ect.

if you could tell me how i would be most grateful.

**Comment by annettek** [comment]
also how to show share count as 0 ift here has been no shares

**Comment by tabalinas** [comment]
For pinterest you should specify the url of an image. Thus, just got the absolute url to you image and provide it to share button.

**Comment by annettek** [comment]
ok i would but the image is different on very page. so i need to use php to generate image url. sorry i don't have mega experience. maybe this one is not for me. pity.

**Comment by tabalinas** [comment]
Regarding zero count: currently, it's by design that zero counts are hidden (native sharers act the same AFAIK).

But you can do the trick adding following css:

```css
.jssocials-share-count-box.jssocials-share-no-count  {
    display: inline-block;
}

.jssocials-share-no-count .jssocials-share-count:before {
    content: '0';
}
```
