### ISSUE TITLE
Share for Tumblr

### ISSUE THREAD

**Issue by MarcelVe** [tabalinas/jssocials#17]
Hi, this plugin is great, but I need some help.
Can you show me how to implement Tumblr in this plugin. (sorry, my english is not so good).
Thank you.

**Comment by tabalinas** [comment]
Hi, Thank you!

You can do it like the following:

```javascript
jsSocials.shares.tumblr = {
    label: "Share",
    logo: "fa fa-tumblr",
    shareUrl: "http://www.tumblr.com/share/link?url={url}",
    countUrl: "http://api.tumblr.com/v2/blog/{url}/info?api_key=put_your_api_key_here",
    getCount: function(data) {
        return data.response.blog.likes;
    }
};

$("#share").jsSocials({
    shares: ["tumblr"]
});
```

Note, that it's impossible to get tumblr shares count not having api_key. So you have request it and put in the countUrl. If you don't care about displaying shares count, just put empty countUrl.

And add stlying, e.g. for the flat theme:

```css
.jssocials-share-tumblr .jssocials-share-link {
  background: #36465d; }
  .jssocials-share-tumblr .jssocials-share-link:hover {
    background: #232e3d; }
```

The better would be to get the src, add tumblr color to `_shares.scss`, and build with grunt, to get css for all themes:

```scss
$share-names: ('twitter', 'facebook', 'googleplus', 'linkedin', 'pinterest', 'email', 'tumblr') !default;
$share-colors: (#00aced, #3b5998, #dd4b39, #007bb6, #cb2027, #3490F3, #36465d) !default;
```
