### ISSUE TITLE
Facebook Like instead of Share Link

### ISSUE THREAD

**Issue by LaravelNick** [tabalinas/jssocials#4]
Is the anyway in which the Facebook link can implement a Facebook Like instead of Facebook Share ?

**Comment by tabalinas** [comment]
Custom facebook likes are [trickier](http://stackoverflow.com/questions/14801757/is-it-possible-to-have-a-custom-facebook-like-button) than shares. It's usually done by native facebook like button.

For now you can doing it by opening facebook like button in new browser tab:

Register following share:

```javascript
jsSocials.shares["facebook-like"]= {
    label: "Like",
    logo: "fa fa-facebook",
    shareUrl: "https://www.facebook.com/v2.3/plugins/like.php?locale=en_US&share=false&show_faces=true&href={url}",
    countUrl: function() {
        return "https://graph.facebook.com/fql?q=SELECT like_count FROM link_stat WHERE url='" + window.encodeURIComponent(this.url) + "'";
    },
    getCount: function(data) {
        return (data.data.length && data.data[0].like_count) || 0;
    }
};
```

Now you can use it like this:

```javascript
$("#share").jsSocials({
    shares: ["facebook-like", "twitter", "googleplus", "linkedin", "pinterest"]
});

```

Also you need to add theming css, e.g. for the flat theme:

```css
.jssocials-share-facebook-like .jssocials-share-link {
  background: #3b5998; }
  .jssocials-share-facebook-like .jssocials-share-link:hover {
    background: #2d4373; }
```

Or even better to get the src, add the color to `_shares.scss`, and build with grunt css for all themes:

```scss
$share-names: ('twitter', 'facebook', 'googleplus', 'linkedin', 'pinterest', 'email', 'facebook-like');
$share-colors: (#00aced, #3b5998, #dd4b39, #007bb6, #cb2027, #0a88ff, #3b5998);
```
