### ISSUE TITLE
Any way to display it vertically?

### ISSUE THREAD

**Issue by BernardoLima** [tabalinas/jssocials#6]
Is there any way to do it currently?

**Comment by tabalinas** [comment]
It's not supported out-of-box right now. 
You can do it with the following css:

```css
.jssocials-share {
    display: block;  
    margin: 0; // or .3em 0 to have vertical gaps between shares
}
```

It's valuable upcoming feature. Lets reopen the issue as an enhancement.
