### ISSUE TITLE
Any built-in support for copy text share?

### ISSUE THREAD

**Issue by vondiplo** [tabalinas/jssocials#67]
Is there any built-in support for copy text share?
If not how can I implement it?

**Comment by tabalinas** [comment]
Good point. For now there is no built-in Copy share.

You could register something like:
```js
        jsSocials.shares.copy = {
            label: "Copy",
            logo: "fa fa-copy",
            shareUrl: "javascript:(function() { window.prompt('Copy to clipboard: Ctrl+C, Enter', '{url}'); return false; })()",
            countUrl: "",
            shareIn: "self"
        };
```

The copying code is taken http://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript. Of course, you can implement copying the way you prefer.

And also some css (for flat theme):

```css
.jssocials-share-email .jssocials-share-link {
  background: #0a88ff; }
  .jssocials-share-email .jssocials-share-link:hover {
    background: #006ed6; }
```

Or to build is automatically for all themes add color to `_shares.scss`, and build with grunt css for all themes:

```scss
$share-names: (..., 'copy');
$share-colors: (..., #0a88ff);
```
